# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pawel/Programy/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/pawel/Programy/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pawel/AGH/MRO/SFP/armadillo-network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pawel/AGH/MRO/SFP/armadillo-network/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/pawel/Programy/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/pawel/Programy/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pawel/AGH/MRO/SFP/armadillo-network/cmake-build-debug/CMakeFiles /home/pawel/AGH/MRO/SFP/armadillo-network/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pawel/AGH/MRO/SFP/armadillo-network/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named armadillo_network

# Build rule for target.
armadillo_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 armadillo_network
.PHONY : armadillo_network

# fast build rule for target.
armadillo_network/fast:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/build
.PHONY : armadillo_network/fast

Layer.o: Layer.cpp.o

.PHONY : Layer.o

# target to build an object file
Layer.cpp.o:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Layer.cpp.o
.PHONY : Layer.cpp.o

Layer.i: Layer.cpp.i

.PHONY : Layer.i

# target to preprocess a source file
Layer.cpp.i:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Layer.cpp.i
.PHONY : Layer.cpp.i

Layer.s: Layer.cpp.s

.PHONY : Layer.s

# target to generate assembly for a file
Layer.cpp.s:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Layer.cpp.s
.PHONY : Layer.cpp.s

NetPoint.o: NetPoint.cpp.o

.PHONY : NetPoint.o

# target to build an object file
NetPoint.cpp.o:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NetPoint.cpp.o
.PHONY : NetPoint.cpp.o

NetPoint.i: NetPoint.cpp.i

.PHONY : NetPoint.i

# target to preprocess a source file
NetPoint.cpp.i:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NetPoint.cpp.i
.PHONY : NetPoint.cpp.i

NetPoint.s: NetPoint.cpp.s

.PHONY : NetPoint.s

# target to generate assembly for a file
NetPoint.cpp.s:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NetPoint.cpp.s
.PHONY : NetPoint.cpp.s

NeuralNet.o: NeuralNet.cpp.o

.PHONY : NeuralNet.o

# target to build an object file
NeuralNet.cpp.o:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NeuralNet.cpp.o
.PHONY : NeuralNet.cpp.o

NeuralNet.i: NeuralNet.cpp.i

.PHONY : NeuralNet.i

# target to preprocess a source file
NeuralNet.cpp.i:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NeuralNet.cpp.i
.PHONY : NeuralNet.cpp.i

NeuralNet.s: NeuralNet.cpp.s

.PHONY : NeuralNet.s

# target to generate assembly for a file
NeuralNet.cpp.s:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/NeuralNet.cpp.s
.PHONY : NeuralNet.cpp.s

Util.o: Util.cpp.o

.PHONY : Util.o

# target to build an object file
Util.cpp.o:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Util.cpp.o
.PHONY : Util.cpp.o

Util.i: Util.cpp.i

.PHONY : Util.i

# target to preprocess a source file
Util.cpp.i:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Util.cpp.i
.PHONY : Util.cpp.i

Util.s: Util.cpp.s

.PHONY : Util.s

# target to generate assembly for a file
Util.cpp.s:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/Util.cpp.s
.PHONY : Util.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/armadillo_network.dir/build.make CMakeFiles/armadillo_network.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... armadillo_network"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... NetPoint.o"
	@echo "... NetPoint.i"
	@echo "... NetPoint.s"
	@echo "... NeuralNet.o"
	@echo "... NeuralNet.i"
	@echo "... NeuralNet.s"
	@echo "... Util.o"
	@echo "... Util.i"
	@echo "... Util.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

